[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm ci', 'cd sistema-gestion && npm ci', 'cd ../backend && npm ci']

[phases.build]
cmds = ['cd sistema-gestion && npm run build']

[start]
cmd = 'cd backend && node server.js'
