[build]
builder = "nixpacks"
buildCommand = "npm install && cd sistema-gestion && npm install && npm run build && cd ../backend && npm install"

[deploy]
startCommand = "cd backend && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
